'use client';

import { useEffect, useState } from 'react';

type Role = 'CSR' | 'NGO';
type Tender = { id:string; title:string; description:string; domain:string; location:string; budget:number; deadline:string; invitedNgos:string[]; status:string; createdBy:string; createdByRole:Role };
type Quote = { id:string; bidderEmail:string; bidderName:string; amount:number; timelineDays:number; proposal:string; status:string };

export default function TendersPage() {
  const [role,setRole]=useState<Role>('CSR'); const [email,setEmail]=useState(''); const [tenders,setTenders]=useState<Tender[]>([]); const [selected,setSelected]=useState<Tender|null>(null); const [quotes,setQuotes]=useState<Quote[]>([]); const [recommendation,setRecommendation]=useState<any>(null); const [message,setMessage]=useState('');
  const [form,setForm]=useState({title:'',description:'',domain:'Education',location:'Tamil Nadu',budget:'',deadline:''}); const [quoteForm,setQuoteForm]=useState({amount:'',timelineDays:'',proposal:''});
  const headers=()=>({'Content-Type':'application/json','x-user-role':role,'x-user-email':email});
  const load=async()=>{if(!email)return;const r=await fetch('/api/tenders',{headers:headers()});const d=await r.json();setTenders(d.tenders||[]);};
  useEffect(()=>{const e=localStorage.getItem('impactbridge_user_email')||'';const r=(localStorage.getItem('impactbridge_user_role') as Role|null)||'CSR';setEmail(e);setRole(r);},[]); useEffect(()=>{if(email)load();},[email,role]);
  const create=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch('/api/tenders',{method:'POST',headers:headers(),body:JSON.stringify({action:'create',...form,budget:Number(form.budget),invitedNgos:[]})});const d=await r.json();setMessage(r.ok?'Tender published successfully.':d.detail||'Unable to publish tender.');if(r.ok){setForm({title:'',description:'',domain:'Education',location:'Tamil Nadu',budget:'',deadline:''});load();}};
  const openTender=async(t:Tender)=>{setSelected(t);setRecommendation(null);const r=await fetch(`/api/tenders?tenderId=${t.id}`,{headers:headers()});const d=await r.json();if(!r.ok){setMessage(d.detail||'Unable to open tender.');return;}setQuotes(d.quotes||[]);};
  const submitQuote=async(e:React.FormEvent)=>{e.preventDefault();if(!selected)return;const r=await fetch('/api/tenders',{method:'POST',headers:headers(),body:JSON.stringify({action:'quote',tenderId:selected.id,bidderName:localStorage.getItem('impactbridge_user_name')||email,...quoteForm,amount:Number(quoteForm.amount),timelineDays:Number(quoteForm.timelineDays)})});const d=await r.json();setMessage(r.ok?'Proposal submitted successfully.':d.detail||'Unable to submit proposal.');if(r.ok){setQuoteForm({amount:'',timelineDays:'',proposal:''});openTender(selected);}};
  const optimize=async()=>{if(!selected)return;const r=await fetch('/api/tenders',{method:'POST',headers:headers(),body:JSON.stringify({action:'optimize',tenderId:selected.id})});const d=await r.json();setRecommendation(d.recommendation||null);};
  const choose=async(id:string)=>{if(!selected)return;const r=await fetch('/api/tenders',{method:'POST',headers:headers(),body:JSON.stringify({action:'select',tenderId:selected.id,quoteId:id})});const d=await r.json();setMessage(r.ok?'Proposal selected and tender awarded.':d.detail||'Unable to select proposal.');if(r.ok)openTender({...selected,status:'AWARDED'});};
  const logout=()=>{window.location.href='/logout';}; const csrOwnTender=role==='CSR'&&selected?.createdBy===email;
  return <main className="min-h-screen bg-slate-50 p-8 text-slate-800"><div className="max-w-7xl mx-auto">
    <header className="flex flex-col md:flex-row justify-between gap-5 items-start md:items-center mb-8"><div><div className="flex items-center gap-3 mb-2"><div className="bg-blue-600 text-white font-bold px-3 py-1.5 rounded-lg">IB</div><span className="text-xl font-extrabold text-slate-900">ImpactBridge</span><span className="text-xs font-semibold bg-blue-50 text-blue-700 px-2.5 py-1 rounded-full">{role==='NGO'?'NGO Partner':'CSR Company'}</span></div><h1 className="text-3xl font-bold text-slate-900">Tender & Quotations</h1><p className="text-slate-500 mt-1">{role==='NGO'?'Create tenders and evaluate CSR proposals.':'Browse open NGO tenders and submit proposals.'}</p></div><div className="flex gap-2 flex-wrap"><button onClick={()=>setRole('CSR')} className={`px-4 py-2 rounded-xl ${role==='CSR'?'bg-blue-600 text-white':'bg-white border'}`}>CSR View</button><button onClick={()=>setRole('NGO')} className={`px-4 py-2 rounded-xl ${role==='NGO'?'bg-blue-600 text-white':'bg-white border'}`}>NGO View</button><button onClick={logout} className="px-4 py-2 rounded-xl bg-red-50 text-red-600 border border-red-200 font-semibold">↪ Logout</button></div></header>
    {message&&<div className="mb-5 bg-blue-50 border border-blue-100 text-blue-700 rounded-xl p-3">{message}</div>}
    {role==='NGO'&&<form onSubmit={create} className="bg-white border rounded-2xl p-6 mb-8 shadow-sm"><h2 className="text-xl font-bold mb-4">Create NGO Tender</h2><div className="grid md:grid-cols-2 gap-4"><input required placeholder="Tender / project title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="border rounded-xl p-3"/><input required min="1" placeholder="Budget (₹)" type="number" value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})} className="border rounded-xl p-3"/><select value={form.domain} onChange={e=>setForm({...form,domain:e.target.value})} className="border rounded-xl p-3"><option>Education</option><option>Healthcare</option><option>Environment</option><option>Rural Development</option></select><input required placeholder="Location" value={form.location} onChange={e=>setForm({...form,location:e.target.value})} className="border rounded-xl p-3"/><input required type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})} className="border rounded-xl p-3"/></div><textarea required placeholder="Project requirements" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="border rounded-xl p-3 w-full mt-4 min-h-24"/><button className="mt-4 bg-blue-600 text-white px-5 py-3 rounded-xl font-semibold">Publish Tender to CSR Network</button></form>}
    <div className="grid lg:grid-cols-2 gap-6"><section><h2 className="text-xl font-bold mb-4">{role==='NGO'?'My NGO Tenders':'Open NGO Tenders'}</h2>{tenders.length===0?<div className="bg-white border rounded-2xl p-8 text-slate-500">No tenders available yet.</div>:tenders.map(t=><button key={t.id} onClick={()=>openTender(t)} className="w-full text-left bg-white border rounded-2xl p-5 mb-3 hover:border-blue-400"><div className="flex justify-between gap-3"><h3 className="font-bold">{t.title}</h3><span className="text-xs bg-green-50 text-green-700 px-2 py-1 rounded-full">{t.status}</span></div><p className="text-sm text-slate-500 mt-2">{t.domain} · {t.location} · ₹{t.budget.toLocaleString('en-IN')}</p><p className="text-sm mt-2">Deadline: {t.deadline}</p><p className="text-xs text-slate-400 mt-1">Created by: {t.createdByRole==='NGO'?'NGO Partner':'CSR Company'}</p></button>)}</section>
    {selected&&<section className="bg-white border rounded-2xl p-6"><h2 className="text-xl font-bold">{selected.title}</h2><p className="text-slate-500 mt-2">{selected.description}</p>{(role==='NGO'&&selected.createdBy===email)||csrOwnTender?<><div className="flex justify-between items-center mt-6 mb-3"><h3 className="font-bold">Received Proposals ({quotes.length})</h3><button onClick={optimize} disabled={!quotes.length} className="bg-slate-900 text-white px-4 py-2 rounded-xl disabled:opacity-50">✨ Optimize</button></div>{recommendation&&<div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-4"><b>Recommended: {recommendation.quote.bidderName}</b><p className="text-sm mt-1">Score: {recommendation.optimizationScore} · ₹{recommendation.quote.amount.toLocaleString('en-IN')} · {recommendation.quote.timelineDays} days</p><button onClick={()=>choose(recommendation.quote.id)} className="mt-2 text-blue-700 font-semibold">Select recommendation</button></div>}{quotes.length===0?<p className="text-slate-500">No proposals yet.</p>:quotes.map(q=><div key={q.id} className="border rounded-xl p-4 mb-3"><div className="flex justify-between gap-3"><b>{q.bidderName}</b><span>₹{q.amount.toLocaleString('en-IN')} · {q.timelineDays} days</span></div><p className="text-sm text-slate-500 mt-2">{q.proposal}</p>{q.status==='SUBMITTED'&&<button onClick={()=>choose(q.id)} className="mt-3 border px-3 py-2 rounded-lg">Select proposal</button>}</div>)}</>:<form onSubmit={submitQuote} className="mt-6 space-y-4"><h3 className="font-bold">Submit Proposal</h3><input required min="1" type="number" placeholder="Proposal amount (₹)" value={quoteForm.amount} onChange={e=>setQuoteForm({...quoteForm,amount:e.target.value})} className="border rounded-xl p-3 w-full"/><input required min="1" type="number" placeholder="Timeline (days)" value={quoteForm.timelineDays} onChange={e=>setQuoteForm({...quoteForm,timelineDays:e.target.value})} className="border rounded-xl p-3 w-full"/><textarea required placeholder="Proposal / implementation plan" value={quoteForm.proposal} onChange={e=>setQuoteForm({...quoteForm,proposal:e.target.value})} className="border rounded-xl p-3 w-full min-h-28"/><button className="bg-blue-600 text-white px-5 py-3 rounded-xl font-semibold">Submit Proposal</button></form>}</section>}
    </div></div></main>;
}
